"""add email to Mj db

Revision ID: 0fcead10c1f1
Revises: 3fdc2f5ef235
Create Date: 2023-08-09 07:10:11.577085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcead10c1f1'
down_revision = '3fdc2f5ef235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mj', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_email', sa.String(length=255), nullable=True))
        batch_op.create_index('idx_customer_email_mj', ['customer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_mj_customer_email'), ['customer_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mj', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mj_customer_email'))
        batch_op.drop_index('idx_customer_email_mj')
        batch_op.drop_column('customer_email')

    # ### end Alembic commands ###
