"""customer_name

Revision ID: 18b23930a38e
Revises: 650a6042f3cf
Create Date: 2023-08-09 07:55:22.676236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b23930a38e'
down_revision = '650a6042f3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mj', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_mj_customer_name'), ['customer_name'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_customer_name'), ['customer_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_customer_name'))
        batch_op.drop_column('customer_name')

    with op.batch_alter_table('mj', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mj_customer_name'))
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
