"""prompt and selectedSize

Revision ID: 3fdc2f5ef235
Revises: c2be6fd9f6a6
Create Date: 2023-08-09 07:01:34.649329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdc2f5ef235'
down_revision = 'c2be6fd9f6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selectedSize', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('prompt', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('prompt')
        batch_op.drop_column('selectedSize')

    # ### end Alembic commands ###
