"""variantsId

Revision ID: 650a6042f3cf
Revises: 0fcead10c1f1
Create Date: 2023-08-09 07:43:47.056727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650a6042f3cf'
down_revision = '0fcead10c1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variantsId', sa.String(length=255), nullable=True))
        batch_op.create_index('idx_variants_id_product', ['variantsId'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_variantsId'), ['variantsId'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_variantsId'))
        batch_op.drop_index('idx_variants_id_product')
        batch_op.drop_column('variantsId')

    # ### end Alembic commands ###
