"""create mj table

Revision ID: 7be2be847da1
Revises: 
Create Date: 2023-07-14 14:51:03.652768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be2be847da1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.Column('imageUrls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('buttons', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('responseAt', sa.DateTime(), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('originatingMessageId', sa.String(length=255), nullable=True),
    sa.Column('buttonMessageId', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mj')
    # ### end Alembic commands ###
