"""new db product 

Revision ID: c2be6fd9f6a6
Revises: e858e448474c
Create Date: 2023-08-09 06:51:50.085944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2be6fd9f6a6'
down_revision = 'e858e448474c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('messageId', sa.String(length=255), nullable=True),
    sa.Column('imageUrl', sa.String(length=255), nullable=True),
    sa.Column('printImageUrl', sa.String(length=255), nullable=True),
    sa.Column('prodImageUrl', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('responseAt', sa.DateTime(), nullable=True),
    sa.Column('updateAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_customer_email_product', ['customer_email'], unique=False)
        batch_op.create_index('idx_customer_id_product', ['customer_id'], unique=False)
        batch_op.create_index('idx_message_id_product', ['messageId'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_customer_email'), ['customer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_messageId'), ['messageId'], unique=False)

    with op.batch_alter_table('mj', schema=None) as batch_op:
        batch_op.drop_index('idx_customer_id')
        batch_op.create_index('idx_customer_id_mj', ['customer_id'], unique=False)
        batch_op.create_index('idx_message_id_mj', ['messageId'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mj', schema=None) as batch_op:
        batch_op.drop_index('idx_message_id_mj')
        batch_op.drop_index('idx_customer_id_mj')
        batch_op.create_index('idx_customer_id', ['customer_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_messageId'))
        batch_op.drop_index(batch_op.f('ix_products_customer_id'))
        batch_op.drop_index(batch_op.f('ix_products_customer_email'))
        batch_op.drop_index('idx_message_id_product')
        batch_op.drop_index('idx_customer_id_product')
        batch_op.drop_index('idx_customer_email_product')

    op.drop_table('products')
    # ### end Alembic commands ###
