"""messageId1

Revision ID: e858e448474c
Revises: 5d560534548c
Create Date: 2023-07-14 15:09:55.046686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e858e448474c'
down_revision = '5d560534548c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mj', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messageId', sa.String(length=255), nullable=True))
        batch_op.drop_index('ix_mj_MessageId')
        batch_op.create_index(batch_op.f('ix_mj_messageId'), ['messageId'], unique=False)
        batch_op.drop_column('MessageId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mj', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MessageId', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_mj_messageId'))
        batch_op.create_index('ix_mj_MessageId', ['MessageId'], unique=False)
        batch_op.drop_column('messageId')

    # ### end Alembic commands ###
